name: Build ruibo Windows

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-ruibo-windows:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "ruibo-build"
      windows-only: true
